# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(833, 614)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 30, 791, 541))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.page.setObjectName("page")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(330, 390, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(0, 0, 0);\n""background-color: rgb(170, 0, 255);")
        self.pushButton.setObjectName("pushButton")
        self.wronguser = QtWidgets.QLabel(self.page)
        self.wronguser.setGeometry(QtCore.QRect(280, 230, 47, 14))
        self.wronguser.setObjectName("wronguser")
        self.user = QtWidgets.QLabel(self.page)
        self.user.setGeometry(QtCore.QRect(280, 190, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.user.setFont(font)
        self.user.setObjectName("user")
        self.passw = QtWidgets.QLabel(self.page)
        self.passw.setGeometry(QtCore.QRect(280, 280, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.passw.setFont(font)
        self.passw.setObjectName("pass")
        self.signinLabel = QtWidgets.QLabel(self.page)
        self.signinLabel.setGeometry(QtCore.QRect(280, 80, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.signinLabel.setFont(font)
        self.signinLabel.setScaledContents(False)
        self.signinLabel.setObjectName("signinLabel")
        self.wrongpass = QtWidgets.QLabel(self.page)
        self.wrongpass.setGeometry(QtCore.QRect(280, 320, 47, 14))
        self.wrongpass.setObjectName("wrongpass")
        self.password = QtWidgets.QLineEdit(self.page)
        self.password.setGeometry(QtCore.QRect(280, 300, 231, 21))
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password.setObjectName("password")
        self.username = QtWidgets.QLineEdit(self.page)
        self.username.setGeometry(QtCore.QRect(280, 210, 231, 21))
        self.username.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.username.setObjectName("username")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("")
        self.page_2.setObjectName("page_2")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(260, 170, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(360, 240, 71, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("submit-successfully.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 833, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.signIn)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Sign In"))
        self.wronguser.setText(_translate("MainWindow", ""))
        self.user.setText(_translate("MainWindow", "UserName"))
        self.passw.setText(_translate("MainWindow", "Password"))
        self.signinLabel.setText(_translate("MainWindow", "User Sign In"))
        self.wrongpass.setText(_translate("MainWindow", ""))
        self.label.setText(_translate("MainWindow", "Signed In successfully"))

    def signIn(self):
        user = "ninizhvania"
        password = "nini123"

        if self.username.text() != user:
            self.wronguser.setText("Wrong User Name")
            self.wronguser.adjustSize()
            self.username.setText("")
        else:
            self.wronguser.setText("")

        if self.password.text() != password:
            self.wrongpass.setText("Wrong Password")
            self.wrongpass.adjustSize()
            self.password.setText("")
        else:
            self.wrongpass.setText("")

        if self.username.text() == user and self.password.text() == password:
            self.stackedWidget.setCurrentIndex(1)
            print("sign in successfully")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
